# -*- coding: utf-8 -*-
"""Unsupervised shopping trend using k-prototype,gower+t-SNE, heatmap,geomaps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DOw0xWRmaGeEUDHc07dSFYScOnI_lrW
"""

import pandas as pd
shop_behv_df=pd.read_csv("/content/shopping_behavior_updated.csv")
shop_behv_df.drop(['Customer ID'],axis=1,inplace=True)
shop_behv_df.head()

for i in shop_behv_df.columns:
  print("i",shop_behv_df[i].value_counts())

"""Doesn't have missing values. Not checking for outliers at this point"""

shop_behv_df.nunique()

#define categorical, numerical features
numeric_distinct_cols=["Previous Purchases"]
numeric_cont_cols=["Age","Purchase Amount (USD)","Review Rating"]
all_cols=shop_behv_df.columns.tolist()
categorical_cols=list(set(all_cols)-set(numeric_distinct_cols)-set(numeric_cont_cols))

shop_behv_df.columns

"""Perform checks on numerical and categorical data

Numerical:

1) Check distribution - should not be skewed

2) check for outliers - what to do with them?

3) check for correlation

4) scale data
"""

import seaborn as sns
import matplotlib.pyplot as plt
fig,axes=plt.subplots(2,2,figsize=(5,10))
axes=axes.flatten()
for i,col in enumerate(numeric_cont_cols):
  sns.boxplot(shop_behv_df[col],ax=axes[i])
plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
fig,axes=plt.subplots(2,2,figsize=(5,10))
axes=axes.flatten()
for i,col in enumerate(numeric_cont_cols):
  sns.histplot(shop_behv_df[col],kde=True,ax=axes[i])
plt.tight_layout()
plt.show()

"""No outliers found or heavy skewness found for numerical data"""



"""Correlation between numeric cols?"""

shop_behv_df[numeric_cont_cols].corr()

"""Checks for categorical data:

1) REmove high cardinality categorical columns- in this case, location, color,Item Purchased have high cardinality. Can't remove directly. Replace with frequency instead?

2)Frequency analysis -which category classes occur less frequently -barchart

3) relationship between categorical columns? - check using crosstab. Chi-square?

"""

import seaborn as sns
import matplotlib.pyplot as plt
n_cols = len(categorical_cols)
fig,axes=plt.subplots(n_cols,1,figsize=(5, n_cols * 5))
axes=axes.flatten()
for i,col in enumerate(categorical_cols):
  sns.barplot(x=shop_behv_df[col].value_counts().index, y=shop_behv_df[col].value_counts().values, ax=axes[i])
  axes[i].set_title(col)
  axes[i].tick_params(axis='x', rotation=90)
plt.tight_layout()
plt.show()

"""Outerwear category has least sales but can't remove it.
Subscription is low - what could be the reason?

"""

#checking relationship between categorical data
from scipy.stats import chi2_contingency
for i in categorical_cols:
  for j in categorical_cols:
    if i!=j:
      #print(i,j)
      #print(pd.crosstab(shop_behv_df[i],shop_behv_df[j]))
      contingency=pd.crosstab(shop_behv_df[i],shop_behv_df[j])
      stat,p,dof,freq=chi2_contingency(contingency)
      if p < 0.05:
        print("significant relationship",i,j)
        contingency.plot(kind='bar',stacked=True)
        plt.show()

"""categorical columns related:

Item Purchased- Category

Shipping Type-Gender

Discount - Promo code

Discount - Gender

Promo code- Gender

Subscription status - Gender

Subscription status - Discount

Subscription status - Promo code


all people who have subscribed have used promo code.
Very few people without subscription got promo code

same is for discount

All subscriptions were by male
Without subscription- both gender equal distr

Remove item purchased-focus on category only
Remove promo code used

discount can be given only via promo code? no sale offers it seems

Are males ordering more than females?
All kind of shipping types are being used by people

could it be that only subscribers get promo code->for discount? Then both promo code and discount could be removed
"""

shop_behv_df.drop(['Discount Applied','Item Purchased','Promo Code Used'],axis=1,inplace=True)

"""For k-means, will have to convert all to numeric

K-mode - can handle categorical data

K-Prototypes:uses K-means for numeric and k-mode for categorical.

Since we do not have missing values, good to go. If we had any missing values - would have imputed or removed as per need
"""

!pip install kmodes

shop_behv_df.head()

#scale numeric columns
#subset of data with just numerical data
numeric_cols=['Age','Purchase Amount (USD)','Review Rating','Previous Purchases']
numeric_shop_df=shop_behv_df[numeric_cols]
original_index = numeric_shop_df.index

#scaling returns numpy array with index lost-The solution is to use the original DataFrame's index and column names
#to reconstruct a new DataFrame from the scaled NumPy array. This allows you to combine it with other processed data correctly.
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler()
numeric_shop_scaled_np=scale.fit_transform(numeric_shop_df)

numeric_shop_scaled_df=pd.DataFrame(numeric_shop_scaled_np,index=original_index,columns=numeric_cols)
#since categorical columns were dropped
categorical_cols = list(shop_behv_df.select_dtypes(include='object').columns)
scaled_shop_behav_df=pd.concat([numeric_shop_scaled_df,shop_behv_df[categorical_cols]],axis=1)
scaled_shop_behav_df.head()

scaled_shop_behav_df.head()

#finding optimum value of k- elbow
from kmodes.kprototypes import KPrototypes
cost_i={}
# Get the updated list of categorical column names and their positions
categorical_cols = list(scaled_shop_behav_df.select_dtypes(include='object').columns)
cat_cols_pos = [scaled_shop_behav_df.columns.get_loc(col) for col in categorical_cols]

for i in [2,3,5,7,10,12,15,20]:
  kp=KPrototypes(n_clusters=i,init='random',verbose=2)
  kp_shop=kp.fit_predict(scaled_shop_behav_df,categorical=cat_cols_pos)
  print(i,kp.cost_)
  cost_i[i]=kp.cost_ #add key value pair in dictionary

#plot cluster k vs cost graph - find elbow optimum k value
print(cost_i)
sns.lineplot(x=list(cost_i.keys()),y=list(cost_i.values()))
plt.show()

"""Between k =3 and 5 there's sharp drop in slope. Since we are checking if adding clusters doesn't affect cost much -check for regions with sharp drop.
k=4,5 trial error. Check with t-SNE later to visualize
"""

!pip install gower
#creating gower distance matrix for all records in df - scaling done already
from gower import gower_matrix
dist_mat=gower_matrix(scaled_shop_behav_df)
#print(dist_mat)
sns.heatmap(dist_mat)

"""Atleast 2 groups/ clusters should be formed with this data (light shade indicates relation)

Now let's pass this to t-SNE for visualisation only. t-SNE is not to be used for clustering when you have categorical data. Just want to understand  the spread of the data
"""

#import tsne
from sklearn.manifold import TSNE
gow_tsne=TSNE(perplexity=30,n_components=2,init='random',random_state=42)
gow_shop_tsne=gow_tsne.fit_transform(dist_mat)
sns.scatterplot(gow_shop_tsne)

"""The original shopping data does have clusters inherently. Atleast 4 clusters are present without a lot of overlapping.Density of the t-SNE scatterplot should not be taken into consideration -incorrect interpretation.

Next step, when k-prototype is applied. Repeat t-sne with gower distance matrix and add color based on cluster defined by k-prototype
"""



# Get the updated list of categorical column names and their positions
categorical_cols = list(scaled_shop_behav_df.select_dtypes(include='object').columns)
cat_cols_pos = [scaled_shop_behav_df.columns.get_loc(col) for col in categorical_cols]

kp=KPrototypes(n_clusters=4,init='random',verbose=2)
kp_shop=kp.fit_predict(scaled_shop_behav_df,categorical=cat_cols_pos)
#converting scaled_shop_behav_df to numpy and passing it to the model might improve performance

#assign cluster to each row of original dataframe
scaled_shop_behav_df['cluster']=kp_shop
scaled_shop_behav_df.head()

"""Now applying t-SNE with clusters formed by k-prototype"""

gow_kp_tsne = TSNE(
    n_components=2,
    perplexity=30,  # Adjust this based on your data. Default is often fine.
    metric='precomputed',
    init='random',
    random_state=42
)

gow_shop_kp_tsne=gow_kp_tsne.fit_transform(dist_mat) #pass gower stance matrix created before
#t-sne keeps index intact so won't be a problem.

# Create a DataFrame for the t-SNE coordinates and cluster labels
tsne_df = pd.DataFrame(data=gow_shop_kp_tsne, columns=['x', 'y'])
tsne_df['cluster'] = scaled_shop_behav_df['cluster']

# Plot the t-SNE visualization
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='x', y='y',
    hue='cluster',
    palette='viridis',
    data=tsne_df,
    legend='full'
)
plt.title('t-SNE Visualization with K-Prototype Clusters (using Gower Distance)')
plt.show()

"""Let's check visually how each feature is impacting the clusters' definition"""

#visualize if numerical data can separate clusters
sns.scatterplot(x=scaled_shop_behav_df['Purchase Amount (USD)'],y=scaled_shop_behav_df['Age'],hue=scaled_shop_behav_df['cluster'])

#visualize if numerical data can separate clusters
sns.scatterplot(x=scaled_shop_behav_df['Review Rating'],y=scaled_shop_behav_df['Age'],hue=scaled_shop_behav_df['cluster'])

#visualize if numerical data can separate clusters
sns.scatterplot(x=scaled_shop_behav_df['Review Rating'],y=scaled_shop_behav_df['Previous Purchases'],hue=scaled_shop_behav_df['cluster'])

#visualize if numerical data can separate clusters
sns.scatterplot(x=scaled_shop_behav_df['Previous Purchases'],y=scaled_shop_behav_df['Age'],hue=scaled_shop_behav_df['cluster'])

"""Based on review rating clusters could have been formed - but couldn't find relationship with pair scatter plot"""

#check for categorical data
# Group by cluster and Subscription Status and count occurrences
subscription_counts = scaled_shop_behav_df.groupby(['cluster', 'Subscription Status']).size().reset_index(name='count')

# Plot the counts
sns.barplot(data=subscription_counts, x='cluster', y='count', hue='Subscription Status')
plt.show()

"""Cluster 0 and 2 could be on opposite ends based on subscription. Cluster 0 has maximum subscribers while cluster 2 has maximum people who have not subscribed"""

subscription_counts = scaled_shop_behav_df.groupby(['cluster', 'Gender']).size().reset_index(name='count')

# Plot the counts
sns.barplot(data=subscription_counts, x='cluster', y='count', hue='Gender')
plt.show()

subscription_counts = scaled_shop_behav_df.groupby(['cluster', 'Category']).size().reset_index(name='count')

# Plot the counts
sns.barplot(data=subscription_counts, x='cluster', y='count', hue='Category')
plt.show()

subscription_counts = scaled_shop_behav_df.groupby(['cluster', 'Size']).size().reset_index(name='count')

# Plot the counts
sns.barplot(data=subscription_counts, x='cluster', y='count', hue='Size')
plt.show()

subscription_counts = scaled_shop_behav_df.groupby(['cluster', 'Season']).size().reset_index(name='count')

# Plot the counts
sns.barplot(data=subscription_counts, x='cluster', y='count', hue='Season')
plt.show()

"""Season heavily defines cluster"""

subscription_counts = scaled_shop_behav_df.groupby(['cluster', 'Shipping Type']).size().reset_index(name='count')

# Plot the counts
sns.barplot(data=subscription_counts, x='cluster', y='count', hue='Shipping Type')
plt.show()

"""Shipping mode defines clusters"""

categorical_cols

subscription_counts = scaled_shop_behav_df.groupby(['cluster', 'Payment Method']).size().reset_index(name='count')

# Plot the counts
sns.barplot(data=subscription_counts, x='cluster', y='count', hue='Payment Method')
plt.show()

"""Payment method influence clusters

Categorical data and clusters relations:

cluster 0 - maximum subscribers; maximum males - as was evident in EDA that all subscribers were male ; max L size; fall season; next day air; cash payment

cluster 1: winter season; store pick up; bank transfer payment;

cluster 2 - min subscribers; max females - consistent with initial EDA that females didn't subscribe much; spring season; free shipping; paypal payment;

cluster3 - accessory category related more; summer season; standard shipping; venmo payment
"""

numeric_cols.append('cluster')

scaled_shop_behav_df[numeric_cols]

#check t-SNE if numerical cols have clear clusters
from sklearn.manifold import TSNE

sne=TSNE(perplexity=30,n_components=2,init='random',random_state=42)
scaled_shop_behav_sne=sne.fit_transform(scaled_shop_behav_df[numeric_cols].drop(['cluster'],axis=1,inplace=False))

scaled_shop_behav_sne

df_tsne = pd.DataFrame(data=scaled_shop_behav_sne, columns=['tsne_1', 'tsne_2'])
#target=scaled_shop_behav_sne['cluster']
#row order is preserved in t-SNE so we can apply survived as hue

sns.scatterplot(
    x='tsne_1', y='tsne_2',
    hue=scaled_shop_behav_df['cluster'], data=df_tsne, palette=['red','blue','green','yellow'])

"""There is some separation based on numeric columns cluster 2,3 but there's lot of overlap with other clusters too. Can't conclude anything here

All of these findings that we did visually for categorical data and numerical data ; t-SNE for numeric data

can also be summarized using centroids- heatmap for numeric data
"""

#heatmap to understand cluster distribution

#step1-retrieve the cluster centroids from your fitted K-prototype model
kp_centroid_np=kp.cluster_centroids_ #this is numpy array gives centroids for each cluster across each feature.
#kp_shop=kp.fit_predict(scaled_shop_behav_df,categorical=[4,5,6,7,8,9,10,11,12,13,14])
print("centroids for all clusters",kp_centroid_np)
#PART A heatmap for numerical data only.
#step1 - extract numerical cluster from above centroid numpy array and create dataframe
print("")
print("centroids for numeric cols",kp_centroid_np[:,:4])
# Ensure numeric_cols only contains the original numeric column names
numeric_cols = ['Age', 'Purchase Amount (USD)', 'Review Rating', 'Previous Purchases']
kp_num_centroid_df=pd.DataFrame(kp_centroid_np[:,:4].astype(float),columns=numeric_cols)

#step2 -heatmap for numeric columns' centroids
sns.heatmap(kp_num_centroid_df, annot=True, cmap='viridis', fmt=".2f",
            yticklabels=[f'Cluster {i}' for i in range(kp.n_clusters)]) #yticklabels is just to display cluster names

#step3 - centroid representation for categorical
#--- Display categorical prototypes in a table ---
categorical_cols = list(scaled_shop_behav_df.select_dtypes(include='object').columns)
kp_cat_centroid_df=pd.DataFrame(kp_centroid_np[:, 4:],
                                 columns=categorical_cols)

#cat_centroids_df = pd.DataFrame(cat_centroids, columns=cat_cols,  index=[f'Cluster {i}' for i in range(kproto.n_clusters)])
kp_cat_centroid_df.head()

kp_cat_centroid_df

"""Earlier using t-SNE local grouping/ spread of data was checked - we visualised applying k-prototype

Factor analysis groups features (columns). It is used to identify latent constructs—underlying, unobserved factors that explain the correlations among a set of related observed variables.
"""

scaled_shop_behav_df.head()

"""Unable to use MCA, FAMD in colab so can't proceed with factor analysis

Want to see sales by location - try to plot it on map
"""

# Install GeoPandas and its dependencies
!pip install geopandas plotly

scaled_shop_behav_df.head()

"""Are clusters formed based on location? - Nope as shown below. So might not be able to use cluster information for location based insights"""

scaled_shop_state_abbrev_Df.groupby('Location')['cluster'].value_counts()

scaled_shop_behav_df['Location'].unique()

map_state_abbrev = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA', 'Colorado': 'CO',
    'Connecticut': 'CT', 'Delaware': 'DE', 'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 'Idaho': 'ID',
    'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS', 'Kentucky': 'KY', 'Louisiana': 'LA',
    'Maine': 'ME', 'Maryland': 'MD', 'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS',
    'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV', 'New Hampshire': 'NH', 'New Jersey': 'NJ',
    'New Mexico': 'NM', 'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK',
    'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC', 'South Dakota': 'SD',
    'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA',
    'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY'
}
filter_location_Df=scaled_shop_behav_df[scaled_shop_behav_df['Location'].isin(map_state_abbrev.keys())].copy()
filter_location_Df['Location']=filter_location_Df['Location'].map(map_state_abbrev)

import geopandas as gpd
import plotly.express as px


# Create the choropleth map
fig = px.choropleth(filter_location__sales_Df,
                    locations=filter_location__sales_Df['Location'], # Column for state abbreviations
                    locationmode="USA-states", # Specifies the location type
                    color=filter_location__sales_Df['Total sales'], # Column to determine the color scale
                    scope="usa", # Limits the map view to the United States
                    color_continuous_scale="YlOrRd", # Sets the color scheme
                    title="Sales by State", # Map title
                    #hover_name="Location", # Shows state name on hover
                    #hover_data={'Total sales': True, 'Location': False} # Customize hover info
                   )

# Display the map in Colab
fig.show()

"""Kansas, florida, hawaii - least earning here.

Does have anything to do with subscription? with gender? with age group? - want this demographic info
"""

scaled_shop_state_abbrev_Df=scaled_shop_behav_df[scaled_shop_behav_df['Location'].isin(map_state_abbrev.keys())].copy()
scaled_shop_state_abbrev_Df['Location']=scaled_shop_state_abbrev_Df['Location'].map(map_state_abbrev)
scaled_shop_state_abbrev_Df['Subscription Status'].replace({"Yes":1, "No":0}, inplace=True)
# Ensure the column is numeric
scaled_shop_state_abbrev_Df['Subscription Status'] = pd.to_numeric(scaled_shop_state_abbrev_Df['Subscription Status'])
scaled_shop_state_abbrev_Df.head()

location_subscription_df=pd.DataFrame(scaled_shop_state_abbrev_Df[['Location','Subscription Status']].groupby('Location')['Subscription Status'].mean().reset_index(name='Subscription avg'))

fig = px.choropleth(location_subscription_df,
                    locations=location_subscription_df['Location'], # Column for state abbreviations
                    locationmode="USA-states", # Specifies the location type
                    color=location_subscription_df['Subscription avg'], # Column to determine the color scale
                    scope="usa", # Limits the map view to the United States
                    color_continuous_scale="YlOrRd", # Sets the color scheme
                    title="Subscription by State", # Map title
                    #hover_name="Location", # Shows state name on hover
                    #hover_data={'Total sales': True, 'Location': False} # Customize hover info
                   )

# Display the map in Colab
fig.show()

"""Kansas has least subscription average as well as least sales. What could be the reason? more number of females? what's the age group?"""

# Ensure 'scaled_shop_state_abbrev_Df' is updated with the one-hot encoded gender columns if not already
scaled_shop_state_abbrev_Df = pd.get_dummies(scaled_shop_behav_df.copy(), columns=['Gender'], dtype=int)
scaled_shop_state_abbrev_Df['Location'] = scaled_shop_state_abbrev_Df['Location'].map(map_state_abbrev)
scaled_shop_state_abbrev_Df = scaled_shop_state_abbrev_Df[scaled_shop_state_abbrev_Df['Location'].isin(map_state_abbrev.values())].copy()


# Calculate the count of females and males per location
location_gender_counts = scaled_shop_state_abbrev_Df.groupby('Location')[['Gender_Female', 'Gender_Male']].sum().reset_index()
location_gender_counts['Female_Male_ratio']=location_gender_counts['Gender_Female']/location_gender_counts['Gender_Male']
display(location_gender_counts.head())

fig = px.choropleth(location_gender_counts,
                    locations=location_gender_counts['Location'], # Column for state abbreviations
                    locationmode="USA-states", # Specifies the location type
                    color=location_gender_counts['Female_Male_ratio'], # Column to determine the color scale
                    scope="usa", # Limits the map view to the United States
                    color_continuous_scale="YlOrRd", # Sets the color scheme
                    title="Female to Male ratio by State", # Map title
                    #hover_name="Location", # Shows state name on hover
                    #hover_data={'Total sales': True, 'Location': False} # Customize hover info
                   )

# Display the map in Colab
fig.show()

"""Kansas has maximum female-male ratio , hence subscription is low as seen in generic trend. Revenue generated from Kansas is also lowest

Texas also has high female-male ratio but subscription avg also on lower side but earining wasn't bad

Florida has poor revenue but subsciption avg was fine.

So revenue isn't just dependent on subscription - or is it even a relevant parameter?

What questions could be answered -

Why are females not subscribing ? - can't be answered based on this dataset

What sizes should I manufacture more or reduce production based on location, target audience-male/female, category

What age group spends more overall? As per each state what age group should be my target audience?

which category is the worst for business, new customers and existing ones won't be ordering?

When and where should I run clear-out sales?

At what frequency should we remind customers to use promo code/ offer new codes to attract more customers? maybe by checking past purchase frequency, time of the year etc?

Clusters are mostly formed on the basis of - Gender, Shipping Type, Payment Method,Season. Maybe Category

I could answer questions like what's the most preferred season for shopping for females and what shipment should I be ready for - plan ahead for timely dispatch, clear blockers.
"""

scaled_shop_behav_df.head()

"""Should I modify features further for simplified strategies? like location->replace with country or state etc.

Color-> form subsets to group similar shades in one group.

Taking it a step further - can I create a model to predict if a new customer added would subscribe or not? how frequently could they purchase? how much will they likely spend?
"""