# -*- coding: utf-8 -*-
"""Fraud detection EDA+sampling+Logistic Reg vs RandomForest vs XGBoost vs LightGBM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4UXm4DB5M0rAQREacKsINEDcQiBHqSb
"""

!pip install cleanlab

import pandas as pd
cc_fraud_df=pd.read_csv("/content/creditcard.csv")
cc_fraud_df.head()

cc_fraud_df.shape

"""v1-v28 PCA components

class- 1 for fraudulent

 'Time' contains the seconds elapsed between each transaction and the first transaction in the dataset.
"""

cc_fraud_df.info()

cc_fraud_df.shape

cc_fraud_df.describe()

cc_fraud_df.isnull().sum()

cc_fraud_df[cc_fraud_df['Amount'].isna()==True]
#1 record has NaN -dropping it
cc_fraud_df.dropna(inplace=True)

cc_fraud_df.drop_duplicates(inplace=True)

import seaborn as sns
sns.scatterplot(x='V16', y='V14', hue='Class', data=cc_fraud_df)

"""Doesn't seem like V1, V2 are the most crucial components - could be good for capturing max variance but for isolating anomalies, there are other features which would do a better job"""



"""Plot PCA -can't find loadings i.e. relation between components and original features without knowing about model used for PCA. how to know which of these give maximum variance of the data?- Since principal components are inherently uncorrelated, the total variance explained is simply the sum of the variances of each individual PC

step1)Calculate the variance of each PC. Use standard statistical methods to find the variance of each column (i.e., each principal component) in your dataset.

step2)Calculate the total variance. Sum the variances of all the principal components to find the total variance explained by the dataset.

Step3)Determine the explained variance ratio. For each principal component, divide its variance by the total variance. The result is the proportion of the total variance captured by that component.

step4)Rank the components. Sort the explained variance ratios in descending order. The component with the highest variance ratio is PC1, the one with the next highest is PC2, and so on.
"""

variances = cc_fraud_df.var()
explained_variance_ratio = variances.sort_values(ascending=False) / variances.sum()
display(explained_variance_ratio)

"""Time, amount,V1,V2,V3 have max variance

No missing values, PCA eliminates multicollinearity already.

Bivariate analysis of each feature wrt Class.
"""

import seaborn as sns
import matplotlib.pyplot as plt
sns.heatmap(cc_fraud_df.corr())

"""These seem to be correlated:
Amount, V7

Amount, V20
"""

#plot correlation wrt Class
corr = cc_fraud_df.corr()
cor_class=corr['Class'].sort_values(ascending=False)
sns.barplot(y=cor_class.index, x=cor_class.values)

"""Max correlation with Class -

Inverse:
V17, V14, V12, V10,V16,V3,V7

Positive corr:V11, V4


"""

#bivariate analysis wrt Class
numeric_columns = cc_fraud_df.drop(columns=["Class"], inplace=False).columns

first_half = numeric_columns[:15]   # Time → V14
second_half = numeric_columns[15:]  # V15 → Amount

plt.figure(figsize=(20, 30))
for i, feature in enumerate(first_half, start=1):
    plt.subplot(5, 3, i)
    sns.boxplot(x="Class", y=feature, data=cc_fraud_df)
    plt.xlabel("Class")
    plt.ylabel(feature)
    plt.title(f"{feature} vs Class")
plt.tight_layout()
plt.show()

plt.figure(figsize=(20, 30))
for i, feature in enumerate(second_half, start=1):
    plt.subplot(5, 3, i)
    sns.boxplot(x="Class", y=feature, data=cc_fraud_df)
    plt.xlabel("Class")
    plt.ylabel(feature)
    plt.title(f"{feature} vs Class")
plt.tight_layout()
plt.show()

"""V14,V12,V11,V10,V9, V7, V3, V4, V16,V17,V18  clearly have some influence on Class labels


Very minimal influence of - Time,V5,V19. Not sure if we should keep these features during selection

Since data is highly imbalanced - Sampling needs to be done

For deciding sampling technique, need to know if the classes can be separated - does it have complex boundaries?


Will do this by using SVM -if a linear line can separate the classes-great.

If model fluctuates a lot with changes in hyperparameters of the model- possibly because of complex boundaries.

If logistic regression vs random forest give drastically different results - complex boundaries

If not, i.e. boundaries aren't clear - use SMOTE+

Can't plot a scatter plot as we have too many features and PCA components - doesn't seem like PC1,PC2 have the strongest relationship with Class. Won't make sense to apply t-SNE on PCA data too.
"""

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, average_precision_score,precision_recall_curve, PrecisionRecallDisplay
import matplotlib.pyplot as plt

X = cc_fraud_df.drop('Class', axis=1)
y = cc_fraud_df['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)


svm_classifier = SVC(kernel='linear')  #with linea, we got low score. Boundaries non-linear ?
#svm_classifier=SVC(kernel='rbf') #with rbf it's even worse!
#svm_classifier=SVC(kernel='poly') #polynomial is also giving bad results
svm_classifier.fit(X_train, y_train)
predict = svm_classifier.predict(X_test)
accuracy = average_precision_score(y_test, predict)
print(f"average_precision_score: {accuracy}")
print(classification_report(y_test, predict))

PrecisionRecallDisplay.from_estimator(svm_classifier, X_test, y_test)
plt.show()

from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
predict = rf.predict(X_test)
accuracy = average_precision_score(y_test, predict)
print(f"average_precision_score: {accuracy}")
print(classification_report(y_test, predict))

PrecisionRecallDisplay.from_estimator(rf, X_test, y_test)
plt.show()

"""With linear/poly/rbf model SVC, precision recall score is low. RandomForest gave significant better score. This could indicate complex boundaries.

Just as an additional check, plotting UMAP for this dataset.
"""

import umap
import matplotlib.pyplot as plt
cc_fraud_df=pd.read_csv("/content/creditcard.csv")
cc_fraud_df.dropna(inplace=True)
cc_fraud_df.drop_duplicates(inplace=True)
X=cc_fraud_df.drop(['Class'],axis=1,inplace=False)
y=cc_fraud_df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.6, random_state=42)

umap_embedding = umap.UMAP(n_components=2,  n_jobs=-1).fit_transform(X_train)
plt.scatter(umap_embedding[:, 0], umap_embedding[:, 1], c=y_train, cmap='Spectral', s=5)
plt.gca().set_aspect('equal', 'datalim')

"""Clearly dataset has complex boundaries

Second thing I need to check - are there lot of mislabeled data points in the dataset? Check by using Confident Learning.

If mislabeled data present - Use ENN for sampling or SMOTE+ENN if large volume of data needed.

So here's my sampling strategy:


1.  Split the data into train, test - to avoid data leak
2.   Remove possibly mislabeled data specifically from majority class because we don't want to reduce minority class population further. Cleanlab will be used
3.   Remove noisy points in train data. Cross check if the algorithm removed any minority class points. Adjust logic such that only majority class data points will be removed. ENN will used.
4.   Scale train data
5.   Since we're dealing with huge volume of data, perform feature selection. SelectKBest used for this.
6.   For feature reduction L1 regression used.
7.   Split majority, minority data sets on train data
8.   On majority subset - apply clustering algorithm like HDBSCAN (because we have complex boundaries, almost uniform density spread). Trial error needed for passing paramaters to HDBSCAN.
9.   From each cluster, pick 50% of the data points at random. Since outliers are a lot in the clusters, will not exclude outliers. Will pick 50%of outliers too.
10.  Merge this sampled majority class subset with minority class subset. Then perform SMOTE for oversampling minority class data points.
11.  Don't forget to scale, use same features on train data!
"""

import cleanlab

import pandas as pd
from sklearn.model_selection import cross_val_predict
# Use on_bad_lines='skip' to skip rows with parsing errors
cc_fraud_df=pd.read_csv("/content/creditcard.csv", on_bad_lines='skip')
cc_fraud_df.shape

from sklearn.ensemble import RandomForestClassifier
from cleanlab.filter import find_label_issues
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_predict
# Use on_bad_lines='skip' to skip rows with parsing errors

cc_fraud_df=pd.read_csv("/content/creditcard.csv", on_bad_lines='skip')

cc_fraud_df.dropna(inplace=True)
cc_fraud_df.drop_duplicates(inplace=True)

# Update the variable name to use the corrected dataframe name
X_train_method23, X_test_method23,y_train_method23,y_test_method23=train_test_split(cc_fraud_df.drop(['Class'],axis=1,inplace=False),cc_fraud_df['Class'],stratify=cc_fraud_df['Class'],test_size=0.2,random_state=42)

train_df_method23=pd.concat([X_train_method23,y_train_method23],axis=1)

train_df_method23.shape

#find mislabeled data points
X=X_train_method23
y=y_train_method23
# Use cross-validation to get out-of-sample predicted probabilities
# This prevents overfitting and gives cleanlab reliable probabilities
model = RandomForestClassifier(n_estimators=50, class_weight='balanced', random_state=42)

#cross_val_predict with method='predict proba' returns predicted probability for each class
pred_probs = cross_val_predict(model, X, y, cv=5, method='predict_proba')

#use cleanlab to find mislabeled data
#find_label_issues returns indices of suspicious data points
label_issues_info = find_label_issues(y.astype(int), pred_probs)

#these are the problematic ones
train_df_method23.iloc[label_issues_info]

mislabeled_entries=train_df_method23.iloc[label_issues_info]
mislabeled_entries['Class'].value_counts()

#to be deleted- Class label 0 which could be incorrectly labeled. 49 records removed
train_df_method23.drop(index=mislabeled_entries[mislabeled_entries['Class']==0].index, inplace=True)

cc_fraud_df.shape

train_df_method23.shape

"""We could further remove noise i.e. data points which could have been incorrectly gathered - could be human error etc. We could use ENN for this. I'm doing this just on majority class as"""

y_train_method23.value_counts()

#checking how many minority samples would ENN remove if it's applied across entire dataset
from imblearn.under_sampling import EditedNearestNeighbours
enn = EditedNearestNeighbours()
X=train_df_method23.drop(['Class'],axis=1,inplace=False)
y=train_df_method23.Class
X_noise_removed, y_noise_removed = enn.fit_resample(X, y)
noise_Removed_df=pd.concat([X_noise_removed, y_noise_removed],axis=1)
y_noise_removed.value_counts()

"""Great, ENN removed records from only majority class. See the results for pre and post y value counts. Class1 is the same

Next, going to sample data- split data into majority and minority sections. Apply sampling on majority class using clustering algorithms.

Which clustering algorithm should I apply on majority class dataset? K-Means? DBSCAN?
Distribution would still remain dense as not a lot of records have been removed. Will check with HDBSCAN as we have high dimensionality.
"""

#DBSCAN needs scaled data. Since we do have outliers, will use RObust scaling
from sklearn.preprocessing import RobustScaler
def robustScale(df):
  X = df.drop(['Class'],axis=1,inplace=False)
  y=df['Class']
  scaler=RobustScaler().set_output(transform="pandas") #since fraud detection relies heavily on outliers
  scaled_cc_X_train_df=scaler.fit_transform(X)

  #used set_output tranfrom=pandas so that it returns df directly. Can merge with y now using same index

  scaled_cc_df=pd.concat([scaled_cc_X_train_df,y],axis=1)
  return scaled_cc_df,scaler
scaled_noise_removed_cc_df,scaler=robustScale(noise_Removed_df)



"""HDBSCAN is taking insanely long to execute over entire dataset. Performing Feature selection to see if time reduces.

We have already removed mislabeled, noisy data points from majority class.
Entire data is scaled except for class  column
"""

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from imblearn.combine import SMOTEENN
import hdbscan
from sklearn.metrics import classification_report

X_scaled = scaled_noise_removed_cc_df.drop(['Class'],axis=1,inplace=False)
y=scaled_noise_removed_cc_df['Class'] #class isn't scaled.
# Step 1: Filter feature selection based on mutual information
selector = SelectKBest(mutual_info_classif, k=15)
X_selected_filter = selector.fit_transform(X_scaled, y)
#X_scaled is dataframe but X_selected_filter is numpy array. indices would have changed! but sequence of records will be the same
selected_indices_filter = selector.get_support(indices=True)

# Step 2: Embedded feature selection with L1-penalized logistic regression.
#will remove features with coef ~0
logreg = LogisticRegression(penalty='l1', solver='liblinear', max_iter=500)
logreg.fit(X_selected_filter, y)
coef_mask = logreg.coef_[0] != 0
X_selected_l1 = X_selected_filter[:, coef_mask]
selected_indices_l1 = selected_indices_filter[coef_mask]

# Create a DataFrame from the NumPy array X_selected_l1, using the original index from y
X_selected_l1_df = pd.DataFrame(X_selected_l1, index=y.index, columns=X_scaled.columns[selected_indices_l1])

# Concatenate X_selected_l1_df and y along the columns axis
method23_train_mislabel_noise_removed_scaled_feature_selected_df = pd.concat([X_selected_l1_df, y], axis=1)

display(method23_train_mislabel_noise_removed_scaled_feature_selected_df.head())

# Separate majority and minority classes in training data
majority_class_df=method23_train_mislabel_noise_removed_scaled_feature_selected_df[method23_train_mislabel_noise_removed_scaled_feature_selected_df['Class']==0]
X_majority_df = majority_class_df.drop(['Class'],axis=1,inplace=False) # X_majority dataframe here, while going forward it's treated as np array

minority_class_df=method23_train_mislabel_noise_removed_scaled_feature_selected_df[method23_train_mislabel_noise_removed_scaled_feature_selected_df['Class']==1]
X_minority_df = minority_class_df.drop(['Class'],axis=1,inplace=False)

X_majority_df.shape

X_minority_df.shape

"""min_cluster_size specifies the minimum number of samples required to form a cluster

in_samples specifies the minimum number of samples in a neighborhood for a point to be considered a core point,

 cluster_selection_method specifies the method used to select clusters from the condensed tree, with 'eom' representing Excess of Mass.

By trial error, checked the 3 parameters-to have as low count of outliers possible (-1) , manageable cluster count.

Refer to the notebook Fraud Detection -Feature selection & sampling techniques trial
"""

# Cluster majority class with HDBSCAN
#need to find optimum ways of creating clusters using HDBSCAN. Experimented in the subsequent cells
clusterer = hdbscan.HDBSCAN(min_cluster_size=60,
                            min_samples=30,
                            cluster_selection_method='eom')
majority_clusters = clusterer.fit_predict(X_majority_df)

# Step 4: Cluster-informed undersampling (sample ~50% from each cluster to reduce majority)
#unique_clusters = np.unique(majority_clusters[majority_clusters != -1])

#since outliers count is quite high 37K+ , excluding outliers will result in information loss. So including -1 outlier category too
unique_clusters = np.unique(majority_clusters)
sampled_majority_indices = []
for cluster in unique_clusters:
    cluster_indices = np.where(majority_clusters == cluster)[0]
    n_samples = max(1, len(cluster_indices) // 2)
    sampled = np.random.choice(cluster_indices, size=n_samples, replace=False)
    sampled_majority_indices.extend(sampled)

from imblearn.over_sampling import SMOTE
#picking the randomly selected indices of the data points from majority class
X_majority_sampled = X_majority_df.iloc[sampled_majority_indices]

# Combine undersampled majority with all minority
X_final_train = np.vstack((X_majority_sampled, X_minority_df))
y_final_train = np.concatenate((np.zeros(len(X_majority_sampled)), np.ones(len(X_minority_df))))

# Step 5: Apply minority oversampling (SMOTE for hybrid over- and under-sampling)
smote = SMOTE(random_state=42)
X_final_resampled, y_final_resampled = smote.fit_resample(X_final_train, y_final_train)

X_final_train.shape

X_final_resampled.shape

#convert X_final_resampled to dataframe
method2_X_final_resampled_df=pd.DataFrame(X_final_resampled,columns=X_scaled.columns[selected_indices_l1])
method2_y_final_resampled_df=pd.DataFrame(y_final_resampled,columns=['Class'])
method2_train_final_resampled_df=pd.concat([method2_X_final_resampled_df,method2_y_final_resampled_df],axis=1)

method2_train_final_resampled_df.shape

method2_train_final_resampled_df.head()

"""What kind of metric should we consider?

Highly imbalanced data

Identifying fraudulent cases is critical. Positive cases to be identified- max

False negative - can't afford!

False positive - to be reviewed by manually if issue is fraudulent , still better to have false positive than false negative

Could use recall, precision , f1 score, area under recall precision curve

"""

X_test_method23.shape

#scaling test data.
#scaled_original_data_test=robustScale(pd.concat([X_test_method23, y_test_method23], axis=1))
#NOOO - CAN'T CALL FUNCTION ON TEST DATA AS IT FITS ON DATA AS WELL.
#scaled_original_data_test=scaler.transform(pd.concat([X_test_method23, y_test_method23], axis=1))
X_scaled_original_data_test=scaler.transform(X_test_method23)
scaled_original_data_test = pd.concat([X_scaled_original_data_test,y_test_method23], axis=1)

scaled_original_data_test.Class.value_counts()

"""Baseline - Logistic Regression. Will use cross validation with k-fold. Give values for C, penalty (l1,l2 regression)

"""

#scaled_original_data_test - what kind of distribution does this have?
#is it that perfectly linearly separabale?
print("scaled original testdata count",scaled_original_data_test.Class.value_counts())

""" SELECT FEATURES IN TEST DATA too!"""

scaled_original_data_test=scaled_original_data_test[method2_train_final_resampled_df.columns]

#logistic regression without sampled data
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import average_precision_score, precision_recall_curve, PrecisionRecallDisplay
from sklearn.metrics import f1_score,confusion_matrix, recall_score,precision_recall_curve,PrecisionRecallDisplay,precision_score, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

#pass scaled data in training and testing df
def logistic_regression(trainingDf, testingDf,columnList,hyperParam_dict):
  if hyperParam_dict:
    LR=LogisticRegression(solver='liblinear',C=hyperParam_dict['C'],penalty=hyperParam_dict['penalty'],random_state=42)
  else:
    LR=LogisticRegression(solver='liblinear',random_state=42)
  LR.fit(trainingDf[columnList],trainingDf['Class'])
  prediction=LR.predict(testingDf[columnList])
  # Calculate the average precision score
  ap_score = average_precision_score(testingDf['Class'], prediction)
  prediction_test_df = pd.DataFrame(prediction, columns=['prediction'], index=testingDf.index)

  PrecisionRecallDisplay.from_estimator(LR, testingDf[columnList], testingDf['Class'])
  plt.show()
  ConfusionMatrixDisplay(confusion_matrix(testingDf['Class'], prediction_test_df)).plot()
  print(f"Average Precision (AUPRC) Score: {ap_score:.4f}")
  print("f1 macro score", f1_score(testingDf['Class'], prediction_test_df, average='macro'))
  return (LR,prediction_test_df)

estimator_sampled_LR,predicted_test_Sampling_LR_df=logistic_regression(method2_train_final_resampled_df, scaled_original_data_test, method2_train_final_resampled_df.columns,{})
y_prob_Sampling_LR = estimator_sampled_LR.predict_proba(method2_train_final_resampled_df)[:,1]

#cross check performance using cross validation
from sklearn.model_selection import StratifiedKFold, cross_val_score, cross_validate
from sklearn.metrics import PrecisionRecallDisplay,precision_recall_curve,average_precision_score, recall_score,f1_score, precision_score, confusion_matrix
import numpy as np

#to ensure even representation of minority class, using stratified CV
# shuffle=True and random_state=42 ensure reproducibility of the shuffle
#shuffle=False where maintaining sequence is important like time series
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scoring_metrics = ['precision', 'recall', 'f1_macro', 'average_precision']

#pass this to logistic regression estimator and check test data

cross_val_results = cross_validate(estimator_sampled_LR,method2_train_final_resampled_df.drop(['Class'],axis=1,inplace=False), method2_train_final_resampled_df['Class'],scoring=scoring_metrics,  cv=skf)
#print(cross_val_results)
print("precision score",cross_val_results['test_precision'])
print("recall score",cross_val_results['test_recall'])
print("f1 macro score",cross_val_results['test_f1_macro'])
print("avg precision",cross_val_results['test_average_precision'])



"""In a dataset where some classes have significantly fewer examples than others, f1_macro is a valuable metric. Unlike f1_weighted, it does not give more weight to the majority classes, so a poor performance on a minority class will have a more significant negative impact on the overall score

Will check if hyperparameter tuning gives better results with both sampled and original training data
"""

#pass any ML model name, data on which RandomSearchCV is to be done -scaled train data
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier as XGBoost
from sklearn.svm import OneClassSVM

#function to pass estimator name and dict of parameters and training data. Should return best parameters
def RandomSearchCV_best_param(estimator,param_dict,trainDf, subset_size=50000):
  # Use a smaller subset of the data for faster tuning
  if len(trainDf) > subset_size:
      trainDf_subset = trainDf.sample(n=subset_size, random_state=42)
  else:
      trainDf_subset = trainDf

  # Reduced cv from 5 to 3 for faster execution
  skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

  if estimator=='LogisticRegression':
    LR=LogisticRegression(random_state=42)
    rscv=RandomizedSearchCV(LR,param_dict,cv=skf,scoring='f1_macro',n_jobs=-1,random_state=42)

  elif estimator=='RandomForest':
    RF = RandomForestClassifier(random_state=42)
    rscv=RandomizedSearchCV(RF,param_dict,cv=skf,scoring='f1_macro',n_jobs=-1,random_state=42)

  elif estimator=='XGBoost':
    XGB=XGBoost(random_state=42)
    rscv=RandomizedSearchCV(XGB,param_dict,n_iter=30,cv=skf,scoring='f1_macro',n_jobs=-1,random_state=42)

  # elif estimator=='OneClassSVM':
  #   OCSVM=OneClassSVM(random_state=42)
  #   rscv=RandomizedSearchCV(OCSVM,param_dict,cv=skf,scoring='f1_macro',n_jobs=-1,random_state=42)

  rscv.fit(trainDf_subset.drop(['Class'],axis=1,inplace=False),trainDf_subset['Class'])
  best_param=rscv.best_params_
  return(best_param)

method2_train_final_resampled_df.shape

#best parameters with sampled data
selected_param_LR_Sampled=RandomSearchCV_best_param('LogisticRegression',
 {'C':10.0 **np.arange(-2,3), 'penalty':['l1','l2','elasticnet'] ,'solver':['liblinear','lbfgs']},
                                         method2_train_final_resampled_df)
print("parameters for logistic regression with sampling",selected_param_LR_Sampled)

#chosen parameters without sampling data {'C': np.float64(10.0), 'penalty': 'l1'}
#chosen parameters with sampled data {'C': np.float64(100.0), 'penalty': 'l2'}

estimator_sampled_tuned_LR,predicted_test_Sampled_tuned_LR_df=logistic_regression(method2_train_final_resampled_df, scaled_original_data_test, method2_train_final_resampled_df.columns,selected_param_LR_Sampled)

#checking with cross validation on sampled training data
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scoring_metrics = ['precision', 'recall', 'f1_macro', 'average_precision']

#pass this to logistic regression estimator and check test data

cross_val_results = cross_validate(estimator_sampled_tuned_LR,method2_train_final_resampled_df.drop(['Class'],axis=1,inplace=False), method2_train_final_resampled_df['Class'],scoring=scoring_metrics,  cv=skf)
#print(cross_val_results)
print("precision score",cross_val_results['test_precision'])
print("recall score",cross_val_results['test_recall'])
print("f1 macro score",cross_val_results['test_f1_macro'])
print("avg precision",cross_val_results['test_average_precision'])

y_prob_Sampled_tuned_LR = estimator_sampled_tuned_LR.predict_proba(method2_train_final_resampled_df)[:,1]

"""compare recall, precisio, f1 score, etc for the 4 scenarios for Logistic regression"""

estimator_sampled_LR.get_params()

estimator_sampled_tuned_LR.get_params()

"""Logistic Regression - precision is slightly better after tuning

Strange with complex boundries , we're getting good results with linear model. How?

Let's check with other models - Random Forest, XGBoost

cHECK With class weight more for class=1/Balanced Random Forest - WITHOUT SAMPLING. USE ORIGINAL DATA. MAYBE JUST SELECT FEATURES AS WE HAVE TOO MUCH DATA
"""



from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import average_precision_score, precision_recall_curve, PrecisionRecallDisplay
from sklearn.metrics import f1_score,confusion_matrix, recall_score,precision_recall_curve,PrecisionRecallDisplay,precision_score, ConfusionMatrixDisplay
import pandas as pd # Ensure pandas is imported
import numpy as np # Ensure numpy is imported
from sklearn.model_selection import StratifiedKFold, cross_val_score, cross_validate


#creating a function to create random forest classifier using
#the given columns(feature selection) and hyperparameters
#function will print how model performed on test data
#function will also print cross validation results on train data
#Returns model used, prediction y_test, y_prob probability score of classification

def RandomF_train_test(trainingDf, testingDf,columnList,hyperParam_dict_RandomF):
  X_train_randomF=trainingDf.drop(['Class'],axis=1,inplace=False)
  y_train_randomF=trainingDf['Class']
  #if hyperparameter no empty
  if  hyperParam_dict_RandomF:
    RF=RandomForestClassifier(n_estimators=hyperParam_dict_RandomF.get('n_estimators', 100),oob_score=True, # Use .get with default values
                            max_depth=hyperParam_dict_RandomF.get('max_depth', None),
                           # min_samples_split=hyperParam_dict_RandomF['min_samples_split'],
                            #min_samples_leaf=hyperParam_dict_RandomF['min_samples_leaf'],
                            max_features=hyperParam_dict_RandomF.get('max_features', 'sqrt'), # Use .get with default values
                            random_state=42,n_jobs=-1)
  else:
    RF=RandomForestClassifier(oob_score=True,random_state=42,n_jobs=-1)
  RF.fit(X_train_randomF,y_train_randomF)

  #checking cross validation performance using train data
  scoring_metrics = ['precision', 'recall', 'f1_macro', 'average_precision']
  # Reduced cv from 5 to 3 for faster execution
  skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

  cross_val_results = cross_validate(RF,trainingDf.drop(['Class'],axis=1,inplace=False), trainingDf['Class'],scoring=scoring_metrics,  cv=skf, n_jobs=-1)
  print("cross_val_results")
  print("precision score",cross_val_results['test_precision'])
  print("recall score",cross_val_results['test_recall'])
  print("f1 macro score",cross_val_results['test_f1_macro'])
  print("avg precision",cross_val_results['test_average_precision'])

  # Use X_train_randomF (features used for fitting) to get predicted probabilities
  y_prob_RF = RF.predict_proba(X_train_randomF)[:,1]

  #checking performance with test data
  X_test=testingDf.drop(['Class'],axis=1,inplace=False)
  y_test=testingDf['Class']
  prediction=RF.predict(X_test)
  # Calculate the average precision score
  ap_score = average_precision_score(y_test, prediction)
  prediction_test_df = pd.DataFrame(prediction, columns=['prediction'], index=X_test.index)
  print(f"Average Precision (AUPRC) Score: {ap_score:.4f}")

  print("recall score",recall_score(y_test, prediction_test_df))
  print("precision score",precision_score(y_test, prediction_test_df))
  print("f1 score",f1_score(y_test, prediction_test_df))

  print("parameters used", RF.get_params())
  ConfusionMatrixDisplay(confusion_matrix(y_test, prediction_test_df)).plot()

  return (RF,prediction,y_prob_RF)

#RF baseline using unscaled unsampled train data
#pass unscaled test data too. y_test is unscaled original test data
estimator_RF_scaled_Sampled,prediction_RF_scaled_Sampled, y_prob_RF_scaled_Sampled =RandomF_train_test(method2_train_final_resampled_df,scaled_original_data_test,method2_train_final_resampled_df.columns,{})

scaled_original_data_test

#hyperparameter tuning for Random Forest using unscaled unsampled train data

selected_param_RF_woSampling=RandomSearchCV_best_param('RandomForest',{
    'n_estimators': [500, 250,1000],
    'max_depth': [None, 50,100],
    #'min_samples_split': [2],
    'min_samples_leaf': [5,20],
    'max_features': ['sqrt', 'log2']
},method2_train_final_resampled_df)
#lost patience to wait, so running on a subset of train data

print("selected parameters (unscaled, unsampled train data) for Random Forest tuning",selected_param_RF_woSampling)

#Checking performance of Random Forest with hyperparameter using unscaled unsampled train datat
estimator_RF_tuned_scaled_Sampled,prediction_RF_tuned_scaled_Sampled, y_prob_RF_tuned_scaled_Sampled =RandomF_train_test(method2_train_final_resampled_df,scaled_original_data_test,method2_train_final_resampled_df.columns,selected_param_RF_woSampling)

"""Overfitting with Random Forest probably? test data gives low recall. How to prevent overfitting in Random Forest??

Repeat the same with XGBoost and hyperparameters without sampling first and then re-check with sampling.

XGBoost uses Boosting unlike Random Forest which uses Bagging. eval set is introduced in XGBoost
"""

#preliminary XGB
from xgboost import XGBClassifier
from sklearn.metrics import average_precision_score, precision_recall_curve, PrecisionRecallDisplay
from sklearn.metrics import f1_score,confusion_matrix, recall_score,precision_recall_curve,PrecisionRecallDisplay,precision_score, ConfusionMatrixDisplay

from sklearn.model_selection import StratifiedKFold, cross_val_score, cross_validate
X_train_XGB, X_val, y_train_XGB, y_val = train_test_split(
    method2_train_final_resampled_df.drop(['Class'],axis=1,inplace=False), method2_train_final_resampled_df['Class'], test_size=0.25, random_state=42
  )
X_test_XGB=scaled_original_data_test.drop(['Class'],axis=1,inplace=False)
y_test_XGB=scaled_original_data_test['Class']

from xgboost import XGBClassifier
from sklearn.metrics import average_precision_score, precision_recall_curve, PrecisionRecallDisplay
from sklearn.metrics import f1_score,confusion_matrix, recall_score,precision_recall_curve,PrecisionRecallDisplay,precision_score, ConfusionMatrixDisplay
from xgboost.callback import EarlyStopping

XGB=XGBClassifier(objective='binary:logistic', seed=42,eval_metric="aucpr")


XGB.fit(X_train_XGB,
            y_train_XGB,
            verbose=True, #to print run details

            eval_set=[(X_val, y_val)]
            )

"""xgb_model in fit() : used for incremental training, also known as "continued" or "resumed" training. Instead of starting a new model from scratch, you provide a pre-trained XGBoost model, and the fit() method adds new boosting rounds to it

Deciding evaluation metric for valuation set:

For balanced binary classification:

logloss (Binary Log-Loss): Log-loss measures the uncertainty of your model's predictions. A lower log-loss value indicates higher confidence in correct predictions and penalizes incorrect ones, especially highly confident false predictions. It is a good choice when you need well-calibrated probability predictions

AUC ROC curve

For imabalanced data, binary classification:

logloss: Can still be used, but interpreting the value requires caution. It still penalizes confident mistakes and is sensitive to calibration, but aucpr often provides a more intuitive sense of performance on the rare class.
"""



#evaluating performance of XGB model:
prediction_XGB_Sampled=XGB.predict(X_test_XGB)
prediction_XGB_Sampled_df=pd.DataFrame(prediction_XGB_Sampled,columns=['prediction'],index=X_test_XGB.index)

ap_score=average_precision_score(y_test_XGB, prediction_XGB_Sampled)
print(f"Average Precision (AUPRC) Score: {ap_score:.4f}")


ConfusionMatrixDisplay(confusion_matrix(y_test_XGB, prediction_XGB_Sampled_df)).plot()

#checking cross validation performance using train data
scoring_metrics = ['precision', 'recall', 'f1_macro', 'average_precision']
# Reduced cv from 5 to 3 for faster execution
skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

cross_val_results = cross_validate(XGB,X_train_XGB, y_train_XGB,scoring=scoring_metrics,  cv=skf, n_jobs=-1)
print("cross_val_results")
print("precision score",cross_val_results['test_precision'])
print("recall score",cross_val_results['test_recall'])
print("f1 macro score",cross_val_results['test_f1_macro'])
print("avg precision",cross_val_results['test_average_precision'])

# Use X_train_randomF (features used for fitting) to get predicted probabilities
y_prob_XGB = XGB.predict_proba(X_train_XGB)[:,1]

"""Annoying trial error begins - hypertuning of XGBoost. Skipped booster=dart (takes insane amount of time to run!!!)"""

#pass any ML model name, data on which RandomSearchCV is to be done -scaled train data
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold, GridSearchCV
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier as XGBoost
from scipy.stats import randint, uniform
#from xgboost.callback import EarlyStopping

param_dict_XGB_round1 = {
    'n_estimators': [500,2000,1200], # Number of boosting rounds
    'max_depth': [10,5,20], # Maximum depth of a tree
    'learning_rate': [0.01,0.1] , # Step size shrinkage used in update to prevent overfitting
    'gamma': [0.01,1.0,0.5], # Minimum loss reduction required to make a further partition on a leaf node
    'reg_alpha': [0.0,0.1,1.0], # L1 regularization term on weights - reduced range
    'reg_lambda': [0.0,0.1,1.0], # L2 regularization term on weights - reduced range
    'min_child_weight': [2,7,1],
    'subsample' : [0.5,1.0],
    'colsample_bytree' : [0.5,1.0],
    'scale_pos_weight': [100,50,2] # Increased range for scale_pos_weight

}

  # Reduced cv from 5 to 3 for faster execution
skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

XGB=XGBoost(booster='gbtree',eval_metric=["aucpr"],n_jobs=-1)
# gsc=GridSearchCV(XGB,param_dict_XGB_round1,cv=skf,scoring='f1_macro',n_jobs=1) # Removed random_state
# gscv.fit(X_train_XGB,y_train_XGB,eval_set=[(X_val, y_val)],verbose=False)
# #rscv=RandomizedSearchCV(XGB,param_dict_XGB_round1,n_iter=30,cv=skf,scoring='f1_macro',n_jobs=1,random_state=42)
# #rscv.fit(X_train_XGB,y_train_XGB,eval_set=[(X_val, y_val)],verbose=False)
# best_param=gscv.best_params_
# print(best_param)

rscv=RandomizedSearchCV(XGB,param_dict_XGB_round1,n_iter=30,cv=skf,scoring='f1_macro',n_jobs=1,random_state=42) # Changed scoring to recall, increased n_iter
rscv.fit(X_train_XGB,y_train_XGB,eval_set=[(X_val, y_val)],verbose=False)
best_param=rscv.best_params_
print(best_param)



"""To reduce overfitting in XGBoost, you can try the following techniques:

*   **Regularization:** XGBoost supports L1 ( `reg_alpha`) and L2 ( `reg_lambda`) regularization on weights. These parameters penalize complex models.
*   **Tree-specific parameters:**
    *   `max_depth`: Limit the maximum depth of the trees.
    *   `min_child_weight`: Minimum sum of instance weight (hessian) needed in a child. This controls overfitting by preventing the growth of trees that are too deep.
    *   `gamma`: Minimum loss reduction required to make a further partition on a leaf node. A larger gamma makes the model more conservative.
*   **Sampling:**
    *   `subsample`: Fraction of samples used for fitting the individual base learners.
    *   `colsample_bytree`, `colsample_bylevel`, `colsample_bynode`: Fraction of features used for fitting the individual base learners at different levels.
*   **Early Stopping:** As you've already implemented, this stops training when the performance on a validation set stops improving.

For tuning hyperparameters, you can use techniques like:

*   **Randomized Search (as you've done):** Efficiently explores a large parameter space.
*   **Grid Search:** Exhaustively searches through a specified subset of hyperparameters. This can be computationally expensive but can be useful for fine-tuning after a randomized search.
*   **Bayesian Optimization:** More advanced techniques that use probabilistic models to find the best hyperparameters more efficiently.

It's important to evaluate your model on a separate test set that was not used for training or validation to get an unbiased estimate of its performance on unseen data.
"""

X_test_XGB=scaled_original_data_test.drop(['Class'],axis=1,inplace=False)
y_test_XGB=scaled_original_data_test['Class']

"""If the above RandomSearchCV takes more than an hour to run, will split up in multiple rounds"""

#tuned XGB model:
selected_param_XBG_Sampling=best_param
XGB_tuned=XGBClassifier(objective='binary:logistic', seed=42,eval_metric=["aucpr"],**selected_param_XBG_Sampling)

XGB_tuned.fit(X_train_XGB,
            y_train_XGB,
            verbose=True, #to print run details

            eval_set=[(X_val, y_val)]
            )

#testing
#evaluating performance of XGB model:
prediction_XGB_Sampled_tuned=XGB_tuned.predict(X_test_XGB)
prediction_XGB_Sampled_tuned_df=pd.DataFrame(prediction_XGB_Sampled_tuned,columns=['prediction'],index=X_test_XGB.index)

ap_score=average_precision_score(y_test_XGB, prediction_XGB_Sampled_tuned)
print(f"Average Precision (AUPRC) Score: {ap_score:.4f}")


ConfusionMatrixDisplay(confusion_matrix(y_test_XGB, prediction_XGB_Sampled_tuned_df)).plot()

"""End of trial error XGB hyperparameter tuning. Best aupcr was still 0.46
Taking average of best readings so far (refer word doc)

{'colsample_bytree': 0.8, 'gamma': 0.3, 'learning_rate': 0.05, 'max_depth': 17, 'min_child_weight': 3, 'n_estimators': 1500, 'reg_lambda': 0.6, 'subsample': 0.5}


"""

#tuned XGB model:
selected_param_XBG_Sampling={'colsample_bytree': 0.8, 'gamma': 0.3, 'learning_rate': 0.05, 'max_depth': 17, 'min_child_weight': 3, 'n_estimators': 1500, 'reg_lambda': 0.6, 'subsample': 0.5}
XGB_tuned_final=XGBClassifier(objective='binary:logistic', seed=42,eval_metric=["aucpr"],**selected_param_XBG_Sampling)
#objective is set to binary logistic because this is binary classification problem. Loss function being minimized is log loss
XGB_tuned_final.fit(X_train_XGB,
            y_train_XGB,
            verbose=True, #to print run details

            eval_set=[(X_val, y_val)]
            )
#testing
#evaluating performance of XGB model:
prediction_XGB_Sampled_tuned=XGB_tuned_final.predict(X_test_XGB)
prediction_XGB_Sampled_tuned_df=pd.DataFrame(prediction_XGB_Sampled_tuned,columns=['prediction'],index=X_test_XGB.index)

ap_score=average_precision_score(y_test_XGB, prediction_XGB_Sampled_tuned)
print(f"Average Precision (AUPRC) Score: {ap_score:.4f}")


ConfusionMatrixDisplay(confusion_matrix(y_test_XGB, prediction_XGB_Sampled_tuned_df)).plot()

#checking cross validation performance using train data
scoring_metrics = ['precision', 'recall', 'f1_macro', 'average_precision']
# Reduced cv from 5 to 3 for faster execution
skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

cross_val_results = cross_validate(XGB_tuned_final,X_train_XGB, y_train_XGB,scoring=scoring_metrics,  cv=skf, n_jobs=-1)
print("cross_val_results")
print("precision score",cross_val_results['test_precision'])
print("recall score",cross_val_results['test_recall'])
print("f1 macro score",cross_val_results['test_f1_macro'])
print("avg precision",cross_val_results['test_average_precision'])

# Use X_train_randomF (features used for fitting) to get predicted probabilities
y_prob_XGB_tuned = XGB_tuned_final.predict_proba(X_train_XGB)[:,1]

#compare best versions of Logistic regression vs Random Forest vs XG Boost

#compare using cross validation results for y_prob and prediction score on test data
#y_prob_XGB_tuned, prediction_XGB_Sampled_tuned_df,
#y_prob_RF_tuned_scaled_Sampled, prediction_RF_tuned_scaled_Sampled,
#y_prob_Sampled_tuned_LR, predicted_test_Sampled_tuned_LR_df

#estimator_RF_tuned_scaled_Sampled,prediction_RF_tuned_scaled_Sampled, y_prob_RF_tuned_scaled_Sampled
#estimator_RF_scaled_Sampled,prediction_RF_scaled_Sampled, y_prob_RF_scaled_Sampled

#y_prob is probability/confidence of the classification
from sklearn.metrics import classification_report
import seaborn as sns
y_test=scaled_original_data_test['Class']
models = {
    "Logistic Regression with sampling without tuning": (y_test, predicted_test_Sampling_LR_df, y_prob_Sampling_LR),
    "Logistic Regression with sampling after tuning": (y_test, predicted_test_Sampled_tuned_LR_df, y_prob_Sampled_tuned_LR),
    "Random Forest with sampling without tuning": (y_test, prediction_RF_scaled_Sampled, y_prob_RF_scaled_Sampled),
    "Random Forest with sampling after tuning": (y_test, prediction_RF_tuned_scaled_Sampled, y_prob_RF_tuned_scaled_Sampled),
    "XGBoost with sampling without tuning": (y_test, prediction_XGB_Sampled_df, y_prob_XGB),
    "XGBoost  with sampling after tuning": (y_test, prediction_XGB_Sampled_tuned_df, y_prob_XGB_tuned)
}

results = []

for name, (yt, yp, ypr) in models.items():
    report = classification_report(yt, yp, output_dict=True)
    #auc = roc_auc_score(yt, ypr)
    #acc = accuracy_score(yt, yp)

    results.append({
        "Model": name,
        #"Accuracy": acc,
        "Precision": report["1"]["precision"],
        "Recall": report["1"]["recall"],
        "F1-score": report["1"]["f1-score"]
        #"ROC-AUC": auc
    })

df_results = pd.DataFrame(results)
print(df_results)

metrics = [ "Precision", "Recall", "F1-score"]

plt.figure(figsize=(12, 6))
df_melted = df_results.melt(id_vars="Model", value_vars=metrics,
                            var_name="Metric", value_name="Score")
sns.barplot(data=df_melted, x="Metric", y="Score", hue="Model")
plt.title("Comparison of Models Performance")
plt.ylim(0, 1)
plt.legend(loc="lower right")
plt.show()

"""Weirdly logistic Regression performed the best. Still unsure if it's just a case of overfitting.

Try out these methods too:

Class sensitive algorithms: class_weight=balanced on original data without sampling, use it with Random Forest. It would still take a lot of time.

Hence testing with LightGBM

BalancedBaggingClassifier on sampled data

Try with from imblearn.ensemble import BalancedRandomForestClassifier

Ensemble learning techniques

Since we're running on free version with limited GPU, try Light GBM
"""

!pip install optuna

import pandas as pd
import numpy as np
credit_df=pd.read_csv("/content/creditcard.csv")
credit_df.drop_duplicates()
credit_df.info()

"""Trying to pass original data for training after splitting as LightGBM is supposed to handle feature engineering, sampling- inbuilt

For highly imbalanced - ratio > 1:1000 sampling might be needed. Let me try without sampling first and just adjust parameters - is_unbalance, scale_pos_weight, max_depth, num_leavs, min_data_in_leaf
"""



from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, average_precision_score,precision_recall_curve, PrecisionRecallDisplay
import matplotlib.pyplot as plt

X = credit_df.drop('Class', axis=1)
y = credit_df['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

#convert y_train to DataFrame
#X_train_df=X_train.to_frame()
y_train_df = y_train.to_frame()
y_test_df=y_test.to_frame()

credit_df.shape

X_train.shape

y_train_df.head()

import lightgbm as lgb
from sklearn.metrics import ConfusionMatrixDisplay,confusion_matrix

# Create LightGBM model
lgbm = lgb.LGBMClassifier(random_state=42, n_jobs=-1)

# Train the model
lgbm.fit(X_train, y_train_df)

# Predict on the test data
y_pred_lgbm = lgbm.predict(X_test)

# Evaluate the model
print("Classification Report for LightGBM:\n")
print(classification_report(y_test_df, y_pred_lgbm))

# Plot confusion matrix
ConfusionMatrixDisplay(confusion_matrix(y_test_df, y_pred_lgbm)).plot()
plt.show()

"""Horrible performance!! Try setting parameters"""

y_train_df.value_counts()

from sklearn.model_selection import RandomizedSearchCV, RepeatedStratifiedKFold
import lightgbm as lgb
from scipy.stats import randint, uniform
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Define the parameter distribution for RandomizedSearchCV
param_dist = {

    #'n_estimators': randint(100, 1000),  # Number of boosting rounds
    'learning_rate': uniform(0.01, 0.1), # Step size shrinkage
    'num_leaves': randint(20, 150),     # Maximum tree leaves for the main tree
    'max_depth': randint(5, 50),        # Maximum tree depth
    'min_child_weight': randint(1, 100), # Minimum number of data needed in a child leaf
    'subsample': uniform(0.5, 1),     # Fraction of samples for fitting the individual base learners
    'colsample_bytree': uniform(0.5, 1), # Fraction of features for fitting the individual base learners
    'reg_alpha': uniform(0, 1),         # L1 regularization term on weights
    'reg_lambda': uniform(0, 1),        # L2 regularization term on weights
    'scale_pos_weight': [y_train.value_counts()[0] / y_train.value_counts()[1], 50, 200], # Handle imbalanced data
}

# Use StratifiedKFold for cross-validation due to imbalanced data
skf = RepeatedStratifiedKFold(n_splits=5, random_state=42)

# Create LightGBM model
lgbm = lgb.LGBMClassifier( is_unbalanced=True,random_state=42, n_jobs=-1)

# Perform RandomizedSearchCV
random_search = RandomizedSearchCV(
    estimator=lgbm,
    param_distributions=param_dist,
    n_iter=50,  # Number of parameter settings that are sampled
    scoring='f1_macro', # Use recall as the primary metric for imbalanced data
    cv=skf,
    n_jobs=-1,
    random_state=42,
    verbose=2
)

# Fit the random search to the training data
random_search.fit(X_train, y_train)

# Print the best parameters and the corresponding score
print(f"Best parameters: {random_search.best_params_}")
print(f"Best recall score: {random_search.best_score_:.4f}")

# Evaluate the best model on the test set
best_lgbm = random_search.best_estimator_
y_pred_lgbm_tuned = best_lgbm.predict(X_test)

print("\nClassification Report for Tuned LightGBM:\n")
print(classification_report(y_test, y_pred_lgbm_tuned))

# Plot confusion matrix for the tuned model
ConfusionMatrixDisplay(confusion_matrix(y_test, y_pred_lgbm_tuned)).plot()
plt.show()

print(best_lgbm)

"""Agenda is to reduce false negative as far as possible.

LGBMClassifier(colsample_bytree=np.float64(0.68433367433137),
               is_unbalanced=True,
               learning_rate=np.float64(0.01808729666171977), max_depth=13,
               min_child_weight=12, n_jobs=-1, num_leaves=148, random_state=42,
               reg_alpha=np.float64(0.17329432007084578),
               reg_lambda=np.float64(0.15643704267108605), scale_pos_weight=50,
               subsample=np.float64(0.7397873591574032))

recall with Fraud: 0.78
precision with fraud: 0.72
false negative: 81
false positive: 112





LGBMClassifier(colsample_bytree=np.float64(0.8266512417960409),
               is_unbalanced=True,
               learning_rate=np.float64(0.09278690037875886), max_depth=48,
               min_child_weight=5, n_jobs=-1, num_leaves=122, random_state=42,
               scale_pos_weight=50, subsample=np.float64(0.5516817211686077))


recall with fraud : 0.77
precision with fraud: 0.84
false negative : 84
false positive: 54





LGBMClassifier(is_unbalanced=True, max_depth=5, n_jobs=-1, num_leaves=77,
               random_state=42, scale_pos_weight=np.float64(546.7))
test:
  false negative :83
  false positive: 5078

  recall with fraud: 0.77
  precision with fraud: 0.05

  LGBMClassifier(is_unbalanced=True, max_depth=7, n_jobs=-1, num_leaves=70,
               random_state=42, scale_pos_weight=200)
test:
  false negative :80
  false positive: 3237

  recall with fraud: 0.78
  precision with fraud: 0.08

I'll check hyperparameter tuning using Optuna- Bayesian optimization
"""

from re import VERBOSE

import numpy as np
import pandas as pd
import optuna
from lightgbm import LGBMClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, roc_auc_score, recall_score, precision_recall_curve, confusion_matrix, ConfusionMatrixDisplay
from lightgbm import early_stopping
# Assume X, y on whole credit card fraud data
X=X_train
y=y_train_df #split in the beginning
def objective(trial):
    # Define search space
    params = {
        'num_leaves': trial.suggest_int('num_leaves', 15, 256),
        'max_depth': trial.suggest_int('max_depth', 4, 50),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 30, 1000),
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 100),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0)
    }
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = []
    for train_idx, test_idx in skf.split(X, y):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
        # Use balanced class weights to mitigate imbalance
        model = LGBMClassifier(**params, class_weight='balanced', n_jobs=-1)
        model.fit(
            X_train, y_train,
            eval_set=[(X_test, y_test)],
            eval_metric='f1_score'

       # callbacks=[early_stopping(stopping_rounds=30)]
        )
        y_pred_proba = model.predict_proba(X_test)[:, 1]
        y_pred=(y_pred_proba > 0.4).astype(int) #threshold at 0.5 for binary
        # Metric: AUC (change to F1 if preferred)
        f1s = f1_score(y_test, y_pred)
        scores.append(f1s)
    return np.mean(scores)

# Start Optuna optimization
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=25)

print("Best params:", study.best_params)

X_train.shape

"""parameters: {'num_leaves': 94, 'max_depth': 42, 'learning_rate': 0.10075392971457457, 'n_estimators': 796, 'min_child_samples': 100, 'subsample': 0.9566422155998704, 'colsample_bytree': 0.5555569810345228}. Best is trial 5 with value: 0.8690109278062529.
Best params: {'num_leaves': 76, 'max_depth': 35, 'learning_rate': 0.139440236840921, 'n_estimators': 718, 'min_child_samples': 94, 'subsample': 0.8847389011695569, 'colsample_bytree': 0.7923917787445951}


"""

# Train the final LightGBM model with the best parameters on the full training data
best_lgbm_final = LGBMClassifier(**study.best_params, class_weight='balanced', n_jobs=-1)
best_lgbm_final.fit(X_train, y_train)

# Evaluate the final model on the test set
y_pred_lgbm_final = best_lgbm_final.predict(X_test)

print("\nClassification Report for Final Tuned LightGBM Model:\n")
print(classification_report(y_test, y_pred_lgbm_final))

# Plot confusion matrix for the final tuned model
ConfusionMatrixDisplay(confusion_matrix(y_test, y_pred_lgbm_final)).plot()
plt.show()

"""Visualization with Optuna"""

from optuna.visualization import

"""Will use Optuna to compare XGBoost, RandomForest, LightGBM,Logistic Regression which one gives better results"""

!pip install optuna
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, average_precision_score,precision_recall_curve, PrecisionRecallDisplay
import matplotlib.pyplot as plt

credit_df=pd.read_csv("/content/creditcard.csv")
credit_df.drop_duplicates()

X = credit_df.drop('Class', axis=1)
y = credit_df['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

#convert y_train to DataFrame
#X_train_df=X_train.to_frame()
y_train_df = y_train.to_frame()
y_test_df=y_test.to_frame()

import numpy as np
import pandas as pd
import optuna
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline


def objective_compare_models(trial):
    classifier_name = trial.suggest_categorical("classifier", ["LGBM", "XGBoost", "RandomForest", "LogisticRegression"])

    if classifier_name == "LGBM":
        params = {
            'num_leaves': trial.suggest_int('num_leaves', 15, 256),
            'max_depth': trial.suggest_int('max_depth', 4, 50),
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),
            'n_estimators': trial.suggest_int('n_estimators', 30, 1000),
            'min_child_samples': trial.suggest_int('min_child_samples', 5, 100),
            'subsample': trial.suggest_float('subsample', 0.5, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
            'class_weight': 'balanced',
            'random_state': 42,
            'n_jobs': -1
        }
        classifier = LGBMClassifier(**params)
    elif classifier_name == "XGBoost":
         params = {
            'n_estimators': trial.suggest_int('n_estimators', 50, 1500),
            'max_depth': trial.suggest_int('max_depth', 3, 20),
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),
            'gamma': trial.suggest_float('gamma', 0, 1),
            'reg_alpha': trial.suggest_float('reg_alpha', 0, 1),
            'reg_lambda': trial.suggest_float('reg_lambda', 0, 1),
            'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
            'subsample': trial.suggest_float('subsample', 0.5, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
            'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1, 500),
            'objective': 'binary:logistic',
            'seed': 42,
            'n_jobs': -1
        }
         classifier = XGBClassifier(**params)
    elif classifier_name == "RandomForest":
        params = {
            'n_estimators': trial.suggest_int('n_estimators', 50, 1500),
            'max_depth': trial.suggest_int('max_depth', 3, 20),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 10),
            'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
            'class_weight': 'balanced',
            'random_state': 42,
            'n_jobs': -1
        }
        classifier = RandomForestClassifier(**params)
    else: # LogisticRegression
        params = {
            'C': trial.suggest_float('C', 1e-4, 1e4, log=True),
            'penalty': trial.suggest_categorical('penalty', ['l1', 'l2']),
            'solver': trial.suggest_categorical('solver', ['liblinear', 'lbfgs']), # lbfgs only supports l2
            'class_weight': 'balanced',
            'random_state': 42,
            'n_jobs': -1
        }
        # Handle solver compatibility with penalty
        if params['penalty'] == 'l1' and params['solver'] == 'lbfgs':
             params['solver'] = 'liblinear' # lbfgs doesn't support l1
        elif params['penalty'] == 'elasticnet':
             params['solver'] = 'saga' # saga supports elasticnet

        classifier = LogisticRegression(**params)

    # Use StratifiedKFold for cross-validation
    skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    f1_macro_scores = []

    # Use a pipeline to scale data within each fold for Logistic Regression
    if classifier_name == "LogisticRegression":
        pipeline = Pipeline([
            ('scaler', StandardScaler()),
            ('classifier', classifier)
        ])
    else:
        pipeline = classifier

    for train_idx, test_idx in skf.split(X_train, y_train):
        X_train_fold, X_test_fold = X_train.iloc[train_idx], X_train.iloc[test_idx]
        y_train_fold, y_test_fold = y_train.iloc[train_idx], y_train.iloc[test_idx]

        pipeline.fit(X_train_fold, y_train_fold)
        y_pred = pipeline.predict(X_test_fold)
        f1_macro_scores.append(f1_score(y_test_fold, y_pred, average='macro'))

    return np.mean(f1_macro_scores)

# Start Optuna optimization
study = optuna.create_study(direction='maximize')
study.optimize(objective_compare_models, n_trials=30)

print("Best params:", study.best_params)

print("Best params:", study.best_params)

#to see all trials conducted
study.trials_dataframe()

#to see how many times each classifier algorithm was run
study.trials_dataframe()['params_classifier'].value_counts()

#if one algorithm was run too many times then that is the clear winner

#find mean score of each algorithm
study.trials_dataframe().groupby('params_classifier')['value'].mean()

# Train the final LightGBM model with the best parameters on the full training data
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
X = credit_df.drop('Class', axis=1)
y = credit_df['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

best_lgbm_final = LGBMClassifier(**study.best_params, class_weight='balanced', n_jobs=-1)
best_lgbm_final.fit(X_train, y_train)

# Evaluate the final model on the test set
y_pred_lgbm_final = best_lgbm_final.predict(X_test)

print("\nClassification Report for Final Tuned LightGBM Model:\n")
print(classification_report(y_test, y_pred_lgbm_final))

# Plot confusion matrix for the final tuned model
ConfusionMatrixDisplay(confusion_matrix(y_test, y_pred_lgbm_final)).plot()
plt.show()

"""Visualization with Optuna"""

from optuna.visualization import plot_param_importances, plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour
plot_param_importances(study).show() #if we had run for just one classifier, then this would have given most important hyperparameter in that algo

plot_optimization_history(study).show() #we could reduce number of trials to 5 perhaps

plot_slice(study).show()

"""Based on the above , we could modify the parameter space reduce it for faster processing?"""

plot_contour(study).show() #okay maybe use this only while using one algorithm

plot_parallel_coordinate(study).show() #didn't work

"""Can Try LightGBM with sampling now if the performance improves"""

