# -*- coding: utf-8 -*-
"""MNIST-read image handwritten digits, t-SNE cluster images.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yObWcXXCbjNCaLkdt9xH9vHEcwbWsnel

How to read image in python and get pixel information in structured data
"""

pip install Pillow numpy

from PIL import Image
import numpy as np

# Open the image file
image_path = '/content/Zero_full (1).jpg'  # Replace with your image file path
img = Image.open(image_path)

# Convert the image to a NumPy array
# For a color image (RGB), this will result in a 3D array (height, width, channels)
# For a grayscale image, it will be a 2D array (height, width)
pixel_data = np.asarray(img)

img

"""The below 3darray .
Total height of image 140 pixels, width 90
each inner array -gives intensity of color in each pixel
[255,255,255] - pixel is white
[0,0,0] - completely black pixel
"""

np.asarray(img)

type(pixel_data)

"""[i][j] will represent which jth pixel from ith row

[i][j][k] will represent r, g or b value where k can take 1,2,3 values
"""

pixel_data[4][1] #first [] is for defining which row of the image are we referring,
# second [i][j] will represent which jth pixel from ith row

pixel_data[3][2][1]

"""each [n1,n2,n3] corresponds to RGB values indicating colour and intensity of the pixel."""

pixel_data[0] #[0] gives first row. Length of array=90 i.e. width of the image

pixel_data[:,0] #gives first column of the image

print(f"Shape of pixel data: {pixel_data.shape}")
print(f"pixel values in the top row:\n{pixel_data[0]}")

"""Here we read just one image . We could read all images and get their pixel values -store the number and pixel tuple as a dataframe to be used. Finding an effective way for loading and transforming 70K images could be a challenge. For now, using the dataset directly which already has this information"""

from sklearn.datasets import fetch_openml
#this dataset gives pixel info for each image of a handwritten digit.
mnist=fetch_openml('mnist_784',version=1,return_X_y=True,as_frame=False) #returns a tuple
#70K records total

#length of tuple is 2 -first part is the image pixel information,
#2nd part is the actual digit ir corresponds to
mnist

mnist[0] #list of all 70K images' pixel information

mnist[1] #digits in the image

mnist[0][0] #pixel of the first image. Images seem to be in greyscale as single digits provided

mnist[1][0] #first digit identified

"""Use t-SNE to see if digits can be distinguished"""

X=mnist[0][:10000] #take first 1000 samples of pixel
y=mnist[1][:10000] # take first 1000 samples of digits

X_std = X/255 #standardize - 255 max value so divide it by 255

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

tsne=TSNE(perplexity=50,n_components=2,init='random')
X_embedded=tsne.fit_transform(X_std)

X_embedded

sns.scatterplot(x=X_embedded[:,0],y=X_embedded[:,1],hue=y)

"""Digits can be distinguished with some overlap"""